# Welcome {.unnumbered}

Це є веб-версія другого видання книги **"R for Data Science"**.
Ця книга запродаждує вступ до науки про дані із R: ви навчитеся тому, як завантажити дані в R, як надати їм найбільш зручну стуктуру, перетворити і візуалізувати (унаочнити).

У цій книжці ви знайдете практикум для відпрацювання навичок в галузі науки про дані.
Подібно до того, як хімік вчиться мити пробірки та упорядковувати лабораторію, ви навчитеся очищати дані та будувати графіки, а також багато інших речей.
Це навички, які дозволяють науці про дані відбуватися, і тут ви знайдете найкращі практики для виконання кожної з цих речей за допомогою R.
Ви дізнаєтеся, як використовувати граматику графіки, грамотно програмувати та відтворювати дослідження для економії часу.
Ви також дізнаєтеся, як керувати когнітивними ресурсами, щоб сприяти відкриттям під час суперечливих моментів, візуалізації та дослідження даних.

This website is and will always be free, licensed under the [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/) License.
If you'd like a physical copy of the book, you can order it on [Amazon](https://www.amazon.com/dp/1492097403?&tag=hadlwick-20).
If you appreciate reading the book for free and would like to give back, please make a donation to [Kākāpō Recovery](https://www.doc.govt.nz/kakapo-donate): the [kākāpō](https://www.youtube.com/watch?v=9T1vfsHYiKY) (which appears on the cover of R4DS) is a critically endangered parrot native to New Zealand; there are only 244 left.

If you speak another language, you might be interested in the freely available translations of the 1st edition:

-   [Spanish](http://es.r4ds.hadley.nz)
-   [Italian](https://it.r4ds.hadley.nz)
-   [Turkish](https://tr.r4ds.hadley.nz)
-   [Portuguese](https://pt.r4ds.hadley.nz)
-   [Українська](https://ua.r4ds.hadley.nz)

You can find suggested answers to exercises in the book at <https://mine-cetinkaya-rundel.github.io/r4ds-solutions>.

Please note that R4DS uses a [Contributor Code of Conduct](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html).
By contributing to this book, you agree to abide by its terms.
