# Preface to the second edition {.unnumbered}

Ласкаво просимо до другого видання «R for Data Science»!
Це суттєве доопрацювання першого видання, в якому вилучено матеріал, який ми більше не вважаємо корисним. Також додано матеріал, який ми хотіли б включити в перше видання, і загалом оновлено текст і код, щоб відобразити зміни в найкращих практиках.
Ми також дуже раді вітати нового співавтора: Міне Четінкая-Рундель, відомого викладача науки про дані та одного з наших колег у Posit (компанія, раніше відома як RStudio).

Нижче наведено короткий огляд найбільших змін:

-   Першу частину книги перейменовано на «Вся гра».
    Мета цього розділу - дати вам приблизну картину «всієї гри» в науці про дані, перш ніж ми зануримося в деталі.

-   Друга частина книги - «Візуалізувати».
    У цій частині більш ґрунтовно висвітлено інструменти візуалізації даних та найкращі практики порівняно з першим виданням.
    Найкращим місцем для отримання всіх деталей все ще залишається [книга ggplot2](http://ggplot2-book.org/), але тепер R4DS охоплює більше найважливіших методів.

-   Третя частина книги тепер називається «Перетворення» і містить нові розділи про числа, логічні вектори та пропущені значення.
    Раніше ці питання були частиною розділу «Перетворення даних», але потребували значно більшого простору для висвітлення всіх деталей.

-   Четверта частина книги називається «Імпорт».
    Це новий набір розділів, який виходить за рамки читання звичайних текстових файлів і включає в себе роботу з електронними таблицями, отримання даних з баз даних, роботу з великими масивами даних, перетворення ієрархічних даних у прямокутні, а також вилучення даних з веб-сайтів.

-   Частина «Програма» залишилася, але була переписана зверху донизу, щоб зосередитися на найбільш важливих частинах написання функцій та ітерацій.
    Написання функцій тепер включає детальну інформацію про те, як виконувати tidyverse-функції (вирішувати проблеми оптимізації оцінок), оскільки це стало набагато простіше і важливіше за останні кілька років.
    Ми додали нову главу про важливі функції базового R, які ви, ймовірно, побачите у «незвичному» R-коді.

-   Моделююча частина була видалена.
    У нас ніколи не було достатньо місця, щоб повною мірою забезпечити повноцінне моделювання, а зараз у нас є набагато кращі ресурси.
    Загалом ми рекомендуємо використовувати пакунки [tidymodels](https://www.tidymodels.org/) та прочитати [Tidy Modeling with R](https://www.tmwr.org/) Макса Куна та Джулії Сілдж (Max Kuhn, Julia Silge).

-   Частина «Спілкування» залишилася, але була ретельно оновлена і тепер містить [Quarto](https://quarto.org/) замість R Markdown.
    Це видання книги написано на Quarto, і це, безумовно, інструмент майбутнього.
